### ISSUE TITLE
Dashboard Page Design

### ISSUE THREAD

**Issue by DatTruong606** [manoa-menu/manoa-menu.github.io#5]

**Comment by jsumiye** [comment]
Great issue Dat!

**Comment by DatTruong606** [comment]
![image](https://github.com/user-attachments/assets/6318ec64-d01b-4966-89b5-0baf5931043c)

A rough sketch of the dashboard page. Open to feedback and/or changes. 
The idea about having pictures for food items is still up in the air but I've placed them there just in case.

**Comment by DatTruong606** [comment]
The recommended section might need to differentiate locations and time. The food court and dining halls have different operation hours so it might be more sensical to have Breakfast/Lunch/Dinner options.
